// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztswxqvquaxypxfzkwey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0c3d4cXZxdWF4eXB4Znprd2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDYwMzIsImV4cCI6MjA1Nzk4MjAzMn0.sI0tqNiLd8X9exsw5ExshGeWmq4Rh9MaUF8jCYFI1oY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);